### ISSUE TITLE
KeyError with group by mixin

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/queue#33]
Seeing the following errors in the log on a relatively simple service (simulator to queue)
```
9/6/2017 8:45:47 AM[2017-09-06 14:45:47.957] NIO [ERROR] [jake queue.ThreadedPoolExecutorRouter] qqq.process_signals failed
9/6/2017 8:45:47 AMTraceback (most recent call last):
9/6/2017 8:45:47 AM  File "/usr/local/lib/python3.5/site-packages/nio/router/base.py", line 375, in notify_signals_to_block
9/6/2017 8:45:47 AM    block_receiver.block.process_signals(signals)
9/6/2017 8:45:47 AM  File "/nio/project/blocks/queue/queue_block.py", line 79, in process_signals
9/6/2017 8:45:47 AM    self.for_each_group(self._push_group, signals)
9/6/2017 8:45:47 AM  File "/usr/local/lib/python3.5/site-packages/nio/block/mixins/group_by/group_by.py", line 80, in for_each_group
9/6/2017 8:45:47 AM    result = target(group_sigs, group, *args, **kwargs)
9/6/2017 8:45:47 AM  File "/nio/project/blocks/queue/queue_block.py", line 162, in _push_group
9/6/2017 8:45:47 AM    self.push(signal, group)
9/6/2017 8:45:47 AM  File "/nio/project/blocks/queue/queue_block.py", line 120, in push
9/6/2017 8:45:47 AM    queue = self._queues[grp]
9/6/2017 8:45:47 AMKeyError: None
```

Queue is configured with capacity and chunk size each of `1` with *no* notification interval (this may be the problem?) and auto reload is *unchecked*. Uniqueness expression is `{{ None }}`. Every second a simulator sends a signal into the queue and this error appears.

**Comment by hansmosh** [comment]
@ssclay Is seeing something similar. It may have to do with persistence.

**Comment by hansmosh** [comment]
After looking at this some more, I believe it's because https://github.com/niolabs/safepickle/issues/3 uses json dump, which makes the `defaultdict` turn into a regular `dict`.

**Comment by tyoungNIO** [comment]
defaultdict support was added to safepickle 0.2.0, I am unable to reproduce this issue using that release. If you are still having this issue, please `pip3 install --upgrade safepickle`
